name: pytorch_gan
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch>=1.8.0
  - torchvision>=0.9.0
  - torchaudio>=0.8.0
  - cudatoolkit=11.6
  - numpy>=1.19.2
  - matplotlib>=3.3.4
  - pillow>=8.1.0
  - tqdm>=4.56.0
  - glob2>=0.7
  - pip>=21.0.0
  - pip:
    - ipykernel>=6.0.0 